import numpy as np
#(1) 加载数据
res = np.loadtxt('./iris.csv')
print(res)
res = np.sort(res)
print(res)
res = np.unique(res)
print(res)
print('统计指标max:\n',np.max(res))
print(res.max(axis=0))
print(res.sum(axis=0))
print(np.cumsum(res,axis=0))
print('111\n',res.cumprod(axis=0))
print(res.var(axis=0))
print(res.argmax(axis=0))